[package]
name = "wla"
version = "0.1.4"
edition = "2021"
authors = ["sts10 <sschlinkert@gmail.com>"]
license = "MIT"
readme = "readme.markdown"
repository = "https://github.com/sts10/wla"
description = "Audit word lists"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
rand = "0.8.5"
unicode-segmentation = "1.10.1"
unicode-normalization = "0.1.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
