[package]
name = "wla"
version = "0.1.3"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
rand = "0.8.5"
unicode-segmentation = "1.10.1"
unicode-normalization = "0.1.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
